// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcdforoqhpvusasrqkxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZGZvcm9xaHB2dXNhc3Jxa3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzg3ODIsImV4cCI6MjA2NTg1NDc4Mn0.8BnSO771cgFfnj6Rw1O0ylre_Sel6_LgAAMFe95ke_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);